version: '2.2'

volumes:
  build:
    driver: local
  cache:
    external: true

services:
  test:
    build: 
      context: ../../
      dockerfile: docker/dev/Dockerfile  
    volumes:
      - cache:/cache
      - build:/build
    links:
      - db
    depends_on: 
      - agent  
    mem_limit: 128m
    cpus: 0.5
    environment:
      DJANGO_SETTINGS_MODULE: todobackend.settings.test
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      TEST_OUTPUT_DIR: /reports

  builder:
    build: 
      context: ../../
      dockerfile: docker/dev/Dockerfile
    volumes:
      - build:/build
    entrypoint: "entrypoint.sh"
    mem_limit: 256m
    cpus: 1
    command: ["pip", "wheel", "--no-index", "-f /build", "."]

  agent:
    image: simorgh1/ansible
    links:
      - db
    environment:
      PROBE_HOST: "db"
      PROBE_PORT: "3306"
    mem_limit: 64m
    cpus: 0.25
    command: ["probe.yml"]

  db: 
    image: mysql:5.6
    hostname: db
    expose:
      - "3306"
    mem_limit: 256m
    cpus: 0.5
    environment:
      MYSQL_ROOT_PASSWORD: password