version: '2.2'

volumes:
  webroot:
    driver: local

services:
  app:
    build: 
      context: ../../
      dockerfile: docker/release/Dockerfile
    links:
      - db
    environment:
      DJANGO_SETTINGS_MODULE: todobackend.settings.release
      MYSQL_HOST: db
      MYSQL_USER: todo
      MYSQL_PASSWORD: password
    volumes:
      - webroot:/var/www/todobackend
    command:
      - uwsgi
      - "--socket /var/www/todobackend/todobackend.sock"
      - "--chmod-socket=666"
      - "--module todobackend.wsgi"
      - "--master"
      - "--die-on-term"
    mem_limit: 128m
    cpus: 0.25  

  test:
    image: jmenga/todobackend-specs
    links:
      - nginx
    environment:
      URL: http://nginx:8000/todos
      JUNIT_REPORT_PATH: /reports/acceptance.xml
      JUNIT_REPORT_STACK: 1
    command: --reporter mocha-jenkins-reporter
    mem_limit: 64m
    cpus: 1

  nginx:
    build: 
      context: .
      dockerfile: Dockerfile.nginx
    links:
      - app
    ports:
      - "8000:8000"
    volumes:
      - webroot:/var/www/todobackend
    mem_limit: 64m
    cpus: 0.25

  db:
    image: mysql:5.6
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: todobackend
      MYSQL_USER: todo
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    mem_limit: 512m
    cpus: 0.5

  agent:
    image: simorgh1/ansible
    links:
      - db
    environment:
      PROBE_HOST: "db"
      PROBE_PORT: "3306"
    command: ["probe.yml"]
    mem_limit: 64m
    cpus: 0.25